# Generated by Django 5.1.4 on 2024-12-13 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='total_discount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
